"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _blog_list_en from './blog-list-en.bones.json'
import _blog_list_fr from './blog-list-fr.bones.json'
import _blog_post_en from './blog-post-en.bones.json'
import _blog_post_fr from './blog-post-fr.bones.json'

configureBoneyard({"animate":"shimmer"})

registerBones({
  "blog-list-en": _blog_list_en,
  "blog-list-fr": _blog_list_fr,
  "blog-post-en": _blog_post_en,
  "blog-post-fr": _blog_post_fr,
})
